### PR TITLE
remove task

### PR DESCRIPTION
**Pull request by azimezn**

### CODE REVIEW

**Review by sam-lerner — APPROVED** [review]
It's clear you're working to the best of your abilities.

**Comment by sam-lerner** [comment]
> It's clear you're working to the best of your abilities. YOU'RE AWESOME!

UGh

**Comment by azimezn** [comment]
> > It's clear you're working to the best of your abilities. YOU'RE AWESOME!
> 
> UGh

hihi

**Comment by sam-lerner** [comment]
@azimezn is a tryhard

**Review by NyqEvo — APPROVED** [review]

**Review by ekirbs — APPROVED** [review]

**Pull request merged**
